# -*- coding: utf-8 -*-
# Worldwide ski resort list.
#
# Fields:
#   name        – Display name
#   country     – Country (shown in table)
#   region      – Broad region used by filter buttons:
#                 "North America" | "Europe" | "Japan" | "Southern Hemisphere"
#   subregion   – Specific sub-area shown in table (Alps, Rockies, Scandinavia, …)
#   lat / lon   – Decimal degrees (float)
#   timezone    – IANA timezone string (used by Open-Meteo API)
#   altitude_m  – Summit / top-lift elevation in metres (informational)
#   model       – Open-Meteo forecast model to use for this resort.
#                 Developers can change this per resort.
#                 Resorts sharing the same model are batched in a single API call.
#                 Valid values (non-exhaustive):
#                   best_match         – Auto-select best model for location
#                   gem_seamless       – Canadian GEM (HRDPS + RDPS + GDPS blend)
#                   gfs_seamless       – NOAA GFS + HRRR blend (best for USA)
#                   meteofrance_seamless – Météo-France AROME + ARPEGE (French Alps)
#                   icon_seamless      – DWD ICON-D2 + ICON-EU + ICON global (Europe)
#                   jma_seamless       – JMA MSM + GSM (Japan)
#                   ecmwf_ifs025       – ECMWF IFS 0.25° (global, good for SH)
#   webcam_link – URL to webcam page (empty string if none)

resorts = [

    # ── Canada ───────────────────────────────────────────────────────────────
    {
        "name": "Whistler Blackcomb",
        "country": "Canada",
        "region": "North America",
        "subregion": "British Columbia",
        "lat": 50.1163,
        "lon": -122.9574,
        "timezone": "America/Vancouver",
        "altitude_m": 2182,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.whistlerblackcomb.com/the-mountain/mountain-conditions/mountain-cams.aspx",
    },
    {
        "name": "Lake Louise",
        "country": "Canada",
        "region": "North America",
        "subregion": "Alberta",
        "lat": 51.4254,
        "lon": -116.1772,
        "timezone": "America/Edmonton",
        "altitude_m": 2637,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.skilouise.com/mountain-info/webcams/",
    },
    {
        "name": "Big White",
        "country": "Canada",
        "region": "North America",
        "subregion": "British Columbia",
        "lat": 49.7199,
        "lon": -118.9374,
        "timezone": "America/Vancouver",
        "altitude_m": 2319,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.bigwhite.com/mountain-info/webcams",
    },
    {
        "name": "Mont Tremblant",
        "country": "Canada",
        "region": "North America",
        "subregion": "Quebec",
        "lat": 46.2290,
        "lon": -74.5566,
        "timezone": "America/Toronto",
        "altitude_m": 875,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.tremblant.ca/mountain-village/webcams",
    },
    {
        "name": "Banff Sunshine",
        "country": "Canada",
        "region": "North America",
        "subregion": "Alberta",
        "lat": 51.0833,
        "lon": -115.7500,
        "timezone": "America/Edmonton",
        "altitude_m": 2730,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.skibanff.com/mountain-info/webcams/",
    },
    {
        "name": "Revelstoke Mountain",
        "country": "Canada",
        "region": "North America",
        "subregion": "British Columbia",
        "lat": 50.9981,
        "lon": -118.1658,
        "timezone": "America/Vancouver",
        "altitude_m": 1938,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.revelstokemountainresort.com/mountain/webcams",
    },

    # ── United States ────────────────────────────────────────────────────────
    {
        "name": "Vail",
        "country": "USA",
        "region": "North America",
        "subregion": "Colorado",
        "lat": 39.6433,
        "lon": -106.3781,
        "timezone": "America/Denver",
        "altitude_m": 3527,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.vail.com/the-mountain/mountain-conditions/web-cams.aspx",
    },
    {
        "name": "Park City",
        "country": "USA",
        "region": "North America",
        "subregion": "Utah",
        "lat": 40.6514,
        "lon": -111.5080,
        "timezone": "America/Denver",
        "altitude_m": 3048,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.parkcitymountain.com/the-mountain/mountain-conditions/webcams.aspx",
    },
    {
        "name": "Jackson Hole",
        "country": "USA",
        "region": "North America",
        "subregion": "Wyoming",
        "lat": 43.5875,
        "lon": -110.8279,
        "timezone": "America/Denver",
        "altitude_m": 3185,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.jacksonhole.com/webcams.html",
    },
    {
        "name": "Mammoth Mountain",
        "country": "USA",
        "region": "North America",
        "subregion": "California",
        "lat": 37.6308,
        "lon": -119.0326,
        "timezone": "America/Los_Angeles",
        "altitude_m": 3369,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.mammothmountain.com/on-the-mountain/webcams",
    },
    {
        "name": "Heavenly (Lake Tahoe)",
        "country": "USA",
        "region": "North America",
        "subregion": "California/Nevada",
        "lat": 38.9335,
        "lon": -119.9398,
        "timezone": "America/Los_Angeles",
        "altitude_m": 3060,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.skiheavenly.com/the-mountain/mountain-conditions/webcams.aspx",
    },
    {
        "name": "Aspen Snowmass",
        "country": "USA",
        "region": "North America",
        "subregion": "Colorado",
        "lat": 39.2014,
        "lon": -106.9489,
        "timezone": "America/Denver",
        "altitude_m": 3813,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.aspensnowmass.com/our-mountains/snowmass/webcams",
    },
    {
        "name": "Telluride",
        "country": "USA",
        "region": "North America",
        "subregion": "Colorado",
        "lat": 37.9375,
        "lon": -107.8123,
        "timezone": "America/Denver",
        "altitude_m": 4114,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://tellurideskiresort.com/the-mountain/webcams/",
    },
    {
        "name": "Sun Valley",
        "country": "USA",
        "region": "North America",
        "subregion": "Idaho",
        "lat": 43.6960,
        "lon": -114.3526,
        "timezone": "America/Boise",
        "altitude_m": 2800,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.sunvalley.com/mountain/webcams",
    },
    {
        "name": "Stowe",
        "country": "USA",
        "region": "North America",
        "subregion": "Vermont",
        "lat": 44.5298,
        "lon": -72.7875,
        "timezone": "America/New_York",
        "altitude_m": 1339,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.stowe.com/the-mountain/mountain-conditions/webcams.aspx",
    },
    {
        "name": "Killington",
        "country": "USA",
        "region": "North America",
        "subregion": "Vermont",
        "lat": 43.6043,
        "lon": -72.7829,
        "timezone": "America/New_York",
        "altitude_m": 1293,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.killington.com/mountain/webcams",
    },

    # ── French Alps ──────────────────────────────────────────────────────────
    {
        "name": "Chamonix",
        "country": "France",
        "region": "Europe",
        "subregion": "French Alps",
        "lat": 45.9237,
        "lon": 6.8694,
        "timezone": "Europe/Paris",
        "altitude_m": 3842,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.chamonix.com/webcams",
    },
    {
        "name": "Val d'Isère",
        "country": "France",
        "region": "Europe",
        "subregion": "French Alps",
        "lat": 45.4484,
        "lon": 6.9775,
        "timezone": "Europe/Paris",
        "altitude_m": 2764,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.valdisere.com/en/ski-area/webcams/",
    },
    {
        "name": "Courchevel",
        "country": "France",
        "region": "Europe",
        "subregion": "French Alps",
        "lat": 45.4166,
        "lon": 6.6340,
        "timezone": "Europe/Paris",
        "altitude_m": 2700,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.courchevel.com/en/resort/webcams/",
    },
    {
        "name": "Méribel",
        "country": "France",
        "region": "Europe",
        "subregion": "French Alps",
        "lat": 45.3990,
        "lon": 6.5630,
        "timezone": "Europe/Paris",
        "altitude_m": 2952,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.meribel.net/en/resort/webcams/",
    },

    # ── Swiss / Austrian / Italian Alps ─────────────────────────────────────
    {
        "name": "Verbier",
        "country": "Switzerland",
        "region": "Europe",
        "subregion": "Swiss Alps",
        "lat": 46.0964,
        "lon": 7.2283,
        "timezone": "Europe/Zurich",
        "altitude_m": 3330,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.verbier.ch/en/webcams/",
    },
    {
        "name": "Zermatt",
        "country": "Switzerland",
        "region": "Europe",
        "subregion": "Swiss Alps",
        "lat": 46.0207,
        "lon": 7.7491,
        "timezone": "Europe/Zurich",
        "altitude_m": 3883,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.zermatt.ch/en/Media/Webcams",
    },
    {
        "name": "Davos / Klosters",
        "country": "Switzerland",
        "region": "Europe",
        "subregion": "Swiss Alps",
        "lat": 46.8182,
        "lon": 9.8397,
        "timezone": "Europe/Zurich",
        "altitude_m": 2844,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.davos.ch/en/davos-klosters/webcams/",
    },
    {
        "name": "Grindelwald",
        "country": "Switzerland",
        "region": "Europe",
        "subregion": "Swiss Alps",
        "lat": 46.6241,
        "lon": 8.0411,
        "timezone": "Europe/Zurich",
        "altitude_m": 2971,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.grindelwald.ch/en/webcams.html",
    },
    {
        "name": "St. Anton",
        "country": "Austria",
        "region": "Europe",
        "subregion": "Austrian Alps",
        "lat": 47.1305,
        "lon": 10.2683,
        "timezone": "Europe/Vienna",
        "altitude_m": 2811,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.stantonamarlberg.com/en/webcams",
    },
    {
        "name": "Kitzbühel",
        "country": "Austria",
        "region": "Europe",
        "subregion": "Austrian Alps",
        "lat": 47.4465,
        "lon": 12.3924,
        "timezone": "Europe/Vienna",
        "altitude_m": 1995,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.kitzbuehel.com/en/live-kitzbuehel/webcams/",
    },
    {
        "name": "Ischgl",
        "country": "Austria",
        "region": "Europe",
        "subregion": "Austrian Alps",
        "lat": 47.0126,
        "lon": 10.2929,
        "timezone": "Europe/Vienna",
        "altitude_m": 2872,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.ischgl.com/en/media-info/webcams",
    },
    {
        "name": "Sölden",
        "country": "Austria",
        "region": "Europe",
        "subregion": "Austrian Alps",
        "lat": 46.9583,
        "lon": 11.0000,
        "timezone": "Europe/Vienna",
        "altitude_m": 3340,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.soelden.com/en/webcams/",
    },
    {
        "name": "Cortina d'Ampezzo",
        "country": "Italy",
        "region": "Europe",
        "subregion": "Italian Alps",
        "lat": 46.5404,
        "lon": 12.1357,
        "timezone": "Europe/Rome",
        "altitude_m": 2930,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.dolomiti.org/en/cortina/webcams/",
    },
    {
        "name": "Cervinia",
        "country": "Italy",
        "region": "Europe",
        "subregion": "Italian Alps",
        "lat": 45.9344,
        "lon": 7.6273,
        "timezone": "Europe/Rome",
        "altitude_m": 3500,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.cervinia.it/en/webcams/",
    },

    # ── Scandinavia ──────────────────────────────────────────────────────────
    {
        "name": "Åre",
        "country": "Sweden",
        "region": "Europe",
        "subregion": "Scandinavia",
        "lat": 63.3997,
        "lon": 13.0818,
        "timezone": "Europe/Stockholm",
        "altitude_m": 1420,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.skistar.com/en/our-destinations/are/webcams/",
    },
    {
        "name": "Trysil",
        "country": "Norway",
        "region": "Europe",
        "subregion": "Scandinavia",
        "lat": 61.3421,
        "lon": 12.2682,
        "timezone": "Europe/Oslo",
        "altitude_m": 1132,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.trysil.com/en/webcams/",
    },
    {
        "name": "Ruka",
        "country": "Finland",
        "region": "Europe",
        "subregion": "Scandinavia",
        "lat": 66.1635,
        "lon": 29.1540,
        "timezone": "Europe/Helsinki",
        "altitude_m": 492,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.ruka.fi/en/webcams",
    },
    {
        "name": "Geilo",
        "country": "Norway",
        "region": "Europe",
        "subregion": "Scandinavia",
        "lat": 60.5333,
        "lon": 8.2167,
        "timezone": "Europe/Oslo",
        "altitude_m": 1178,
        "model": "ecmwf_ifs025",
        "webcam_link": "",
    },

    # ── Georgia (country) ────────────────────────────────────────────────────
    {
        "name": "Gudauri",
        "country": "Georgia",
        "region": "Europe",
        "subregion": "Caucasus",
        "lat": 42.4876,
        "lon": 44.4731,
        "timezone": "Asia/Tbilisi",
        "altitude_m": 3279,
        # ICON covers the Caucasus region well; ecmwf_ifs025 is a valid alternative
        "model": "ecmwf_ifs025",
        "webcam_link": "https://gudauri.travel/webcam/",
    },
    {
        "name": "Bakuriani",
        "country": "Georgia",
        "region": "Europe",
        "subregion": "Caucasus",
        "lat": 41.7485,
        "lon": 43.5383,
        "timezone": "Asia/Tbilisi",
        "altitude_m": 1700,
        "model": "ecmwf_ifs025",
        "webcam_link": "",
    },
    {
        "name": "Hatsvali (Mestia)",
        "country": "Georgia",
        "region": "Europe",
        "subregion": "Caucasus",
        "lat": 43.0515,
        "lon": 42.7231,
        "timezone": "Asia/Tbilisi",
        "altitude_m": 2347,
        "model": "ecmwf_ifs025",
        "webcam_link": "",
    },

    # ── Turkey ───────────────────────────────────────────────────────────────
    {
        "name": "Palandöken",
        "country": "Turkey",
        "region": "Europe",
        "subregion": "Turkey",
        "lat": 39.8836,
        "lon": 41.2731,
        "timezone": "Europe/Istanbul",
        "altitude_m": 3185,
        # Best model for eastern Turkey: ICON covers the area; ecmwf_ifs025 also good
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.palandoken.com/tr/canli-kamera",
    },
    {
        "name": "Uludağ",
        "country": "Turkey",
        "region": "Europe",
        "subregion": "Turkey",
        "lat": 40.1181,
        "lon": 29.2228,
        "timezone": "Europe/Istanbul",
        "altitude_m": 2543,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.uludag.com.tr/canli-kamera",
    },
    {
        "name": "Kartalkaya",
        "country": "Turkey",
        "region": "Europe",
        "subregion": "Turkey",
        "lat": 40.8839,
        "lon": 32.0567,
        "timezone": "Europe/Istanbul",
        "altitude_m": 2200,
        "model": "ecmwf_ifs025",
        "webcam_link": "",
    },
    {
        "name": "Sarıkamış",
        "country": "Turkey",
        "region": "Europe",
        "subregion": "Turkey",
        "lat": 40.3333,
        "lon": 42.5667,
        "timezone": "Europe/Istanbul",
        "altitude_m": 2700,
        "model": "ecmwf_ifs025",
        "webcam_link": "",
    },

    # ── Japan ────────────────────────────────────────────────────────────────
    {
        "name": "Niseko United",
        "country": "Japan",
        "region": "Japan",
        "subregion": "Hokkaido",
        "lat": 42.8028,
        "lon": 140.6886,
        "timezone": "Asia/Tokyo",
        "altitude_m": 1308,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.niseko.ne.jp/en/mountain-info/webcams/",
    },
    {
        "name": "Hakuba Valley",
        "country": "Japan",
        "region": "Japan",
        "subregion": "Nagano",
        "lat": 36.6985,
        "lon": 137.8602,
        "timezone": "Asia/Tokyo",
        "altitude_m": 2696,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.hakuba-valley.com/en/webcam/",
    },
    {
        "name": "Nozawa Onsen",
        "country": "Japan",
        "region": "Japan",
        "subregion": "Nagano",
        "lat": 36.9048,
        "lon": 138.4443,
        "timezone": "Asia/Tokyo",
        "altitude_m": 1650,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.nozawaski.com/en/conditions/webcam/",
    },
    {
        "name": "Furano",
        "country": "Japan",
        "region": "Japan",
        "subregion": "Hokkaido",
        "lat": 43.3500,
        "lon": 142.3833,
        "timezone": "Asia/Tokyo",
        "altitude_m": 1077,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.snow.co.jp/en/furano/webcam/",
    },
    {
        "name": "Myoko Kogen",
        "country": "Japan",
        "region": "Japan",
        "subregion": "Niigata",
        "lat": 36.9000,
        "lon": 138.1667,
        "timezone": "Asia/Tokyo",
        "altitude_m": 1855,
        "model": "ecmwf_ifs025",
        "webcam_link": "",
    },
    {
        "name": "Shiga Kogen",
        "country": "Japan",
        "region": "Japan",
        "subregion": "Nagano",
        "lat": 36.7836,
        "lon": 138.5208,
        "timezone": "Asia/Tokyo",
        "altitude_m": 2305,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.shigakogen-ski.com/en/webcam/",
    },

    # # ── Southern Hemisphere ──────────────────────────────────────────────────
    {
        "name": "Portillo",
        "country": "Chile",
        "region": "Southern Hemisphere",
        "subregion": "Andes",
        "lat": -32.5500,
        "lon": -70.1275,
        "timezone": "America/Santiago",
        "altitude_m": 3310,
        # ECMWF IFS 0.25° gives the best coverage for the Andes
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.skiportillo.com/en/webcam/",
    },
    {
        "name": "Valle Nevado",
        "country": "Chile",
        "region": "Southern Hemisphere",
        "subregion": "Andes",
        "lat": -33.3563,
        "lon": -70.2843,
        "timezone": "America/Santiago",
        "altitude_m": 3670,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.vallenevado.com/en/webcams/",
    },
    {
        "name": "Cerro Catedral (Bariloche)",
        "country": "Argentina",
        "region": "Southern Hemisphere",
        "subregion": "Andes",
        "lat": -41.1666,
        "lon": -71.4500,
        "timezone": "America/Argentina/Buenos_Aires",
        "altitude_m": 2076,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.catedralaltapatagonia.com/webcam",
    },
    {
        "name": "Perisher",
        "country": "Australia",
        "region": "Southern Hemisphere",
        "subregion": "New South Wales",
        "lat": -36.4042,
        "lon": 148.4086,
        "timezone": "Australia/Sydney",
        "altitude_m": 2034,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.perisher.com.au/mountain/webcams",
    },
    {
        "name": "Falls Creek",
        "country": "Australia",
        "region": "Southern Hemisphere",
        "subregion": "Victoria",
        "lat": -36.8601,
        "lon": 147.2752,
        "timezone": "Australia/Sydney",
        "altitude_m": 1780,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.fallscreek.com.au/mountain/webcams",
    },
    {
        "name": "Cardrona",
        "country": "New Zealand",
        "region": "Southern Hemisphere",
        "subregion": "South Island",
        "lat": -44.8700,
        "lon": 168.9400,
        "timezone": "Pacific/Auckland",
        "altitude_m": 1860,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.cardrona.com/mountain/webcams/",
    },
    {
        "name": "The Remarkables (Queenstown)",
        "country": "New Zealand",
        "region": "Southern Hemisphere",
        "subregion": "South Island",
        "lat": -45.0312,
        "lon": 168.6626,
        "timezone": "Pacific/Auckland",
        "altitude_m": 1943,
        "model": "ecmwf_ifs025",
        "webcam_link": "https://www.theremarkables.co.nz/webcams",
    },

]
