mountains = [
    {
        "name": "Mont Comi",
        "region": "B.-St-L.",
        "lat": "48.46575",
        "lon": "-68.21036",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.ipcamlive.com/5a348b49b950e"
    },
    {
        "name": "Mont Sutton",
        "region": "Estrie",
        "lat": "45.08195",
        "lon": "-72.54837",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://montsutton.com/en/the-mountain/ski-conditions/"
    },
    {
        "name": "Mont Lyall",
        "region": "Gaspésie",
        "lat": "48.80412",
        "lon": "-66.08622",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://avalanchequebec.ca/en/webcam/"
    },
    {
        "name": "Mont Gosford",
        "region": "Estrie",
        "lat": "45.30179",
        "lon": "-70.86683",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Hereford",
        "region": "Estrie",
        "lat": "45.08229",
        "lon": "-71.60047",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Albert",
        "region": "Gaspésie",
        "lat": "48.93293",
        "lon": "-66.17872",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://avalanchequebec.ca/en/webcam/"
    },
    {
        "name": "Massif du Sud",
        "region": "Ch.-App.",
        "lat": "46.62235",
        "lon": "-70.48768",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://rtsp.me/embed/n82fTnbQ/"
    },
    {
        "name": "Mont Edouard",
        "region": "S.–L.-St-J.",
        "lat": "48.15209",
        "lon": "-70.28355",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.montedouard.com/fr/cameradirect"
    },
    {
        "name": "Massif de Charlevoix",
        "region": "Cap.-N.",
        "lat": "47.27839",
        "lon": "-70.61007",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.lemassif.com/fr/montagne/ete/meteo-et-webcams"
    },
    {
        "name": "Mont Orford",
        "region": "Estrie",
        "lat": "45.31228",
        "lon": "-72.24160",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Saint-Anne",
        "region": "Cap.-N.",
        "lat": "47.08696",
        "lon": "-70.93293",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://mont-sainte-anne.com/en/alpine-skiing-webcams/"
    },
    {
        "name": "Montagne Noire",
        "region": "Lan.",
        "lat": "46.24366",
        "lon": "-74.29391",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont des Allemands",
        "region": "S.–L.-St-J.",
        "lat": "49.17056",
        "lon": "-71.47667",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Saint-Mathieu",
        "region": "Maur.",
        "lat": "46.59737",
        "lon": "-72.83955",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://montstmathieu.com/webcams/"
    },
    {
        "name": "Mont Alta",
        "region": "Laur.",
        "lat": "46.03834",
        "lon": "-74.24119",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Gallix",
        "region": "C.-N.",
        "lat": "50.16871",
        "lon": "-66.71735",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Plante (Val-David-Val-Morin)",
        "region": "Laur.",
        "lat": "46.02857",
        "lon": "-74.19882",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Hog's Back",
        "region": "Gaspésie",
        "lat": "48.85675",
        "lon": "-66.10941",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://avalanchequebec.ca/en/webcam/"
    },
    {
        "name": "Mont Veyrier",
        "region": "C.-N.",
        "lat": "51.53338",
        "lon": "-68.08214",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Mont Valin",
        "region": "S.–L.-St-J.",
        "lat": "48.61678",
        "lon": "-70.79904",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": ""
    },
    {
        "name": "Le Valinouët",
        "region": "S.–L.-St-J.",
        "lat": "48.63892",
        "lon": "-70.89714",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://valinouet.qc.ca/en/live-cam-weather/",
    },
    {
        "name": "Ski Bromont",
        "region": "Estrie",
        "lat": "45.28877",
        "lon": "-72.63882",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.bromontmontagne.com/en/webcams/",
    },
    {
        "name": "Owl's Head",
        "region": "Estrie",
        "lat": "45.06267",
        "lon": "-72.29796",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://owlshead.com/en/ski-conditions/",
    },
    {
        "name": "Mont Blanc",
        "region": "Laur.",
        "lat": "46.10164",
        "lon": "-74.48507",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Mont Tremblant",
        "region": "Laur.",
        "lat": "46.22896",
        "lon": "-74.55661",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.tremblant.ca/mountain-village/webcams",
    },
    {
        "name": "Mont Shefford",
        "region": "Estrie",
        "lat": "45.36228",
        "lon": "-72.61082",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Mont Adstock",
        "region": "Ch.-App.",
        "lat": "46.03107",
        "lon": "-71.20695",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Jay Peak",
        "region": "VT",
        "lat": "44.91583",
        "lon": "-72.54750",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://jaypeakresort.com/resort/photo-day",
    },
    {
        "name": "Touski Espace Plein Air",
        "region": "Laur.",
        "lat": "46.19029",
        "lon": "-74.35254",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "",
    },
    {
        "name": "Parc national de la Jacques‑Cartier",
        "region": "Cap.-N.",
        "lat": "47.20756",
        "lon": "-71.38161",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.sepaq.com/pq/jac/webcam.dot",
    },
     {
        "name": "Vallée Bras du Nord",
        "region": "Cap.-N.",
        "lat": "47.07570",
        "lon": "-71.91778",
        "snow": 0.0,
        "rain": 0.0,
        "freezing_rain": 0.0,
        "ice_pellets": 0.0,
        "hrdps_link": "",
        "gdps_link": "",
        "rdps_link": "",
        "nam_link": "",
        "gfs_link": "",
        "google_map_link": "",
        "windy_link": "",
        "webcam_link": "https://www.sepaq.com/pq/jac/webcam.dot",
    }
]
